### ISSUE TITLE
day1: technical detail beyond scope?

### ISSUE THREAD

**Issue by kortschak** [UofABioinformaticsHub/Spring_Into_Bioinformatics#5]
In day1/06 there is "For those who are familiar with these things, a `data.frame` uses S3 methods, whilst a `DataFrame` uses S4 methods, If that made no sense, there's no need to worry as this is not relevant information for those at a more entry level."

I don't think this adds anything and will, despite the caveat, trip people over.

Views?

**Comment by smped** [comment]
Yeah. I'll edit & rephrase.
